# -*- coding: utf-8 -*-
"""20ExecPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16YD6nm1jO97VyAk2decC3ZNF3RnfgotM
"""

#Exec1 Laços de Repetição - Vinicius Queiroz Santos
for numero in range(1,11):
  print(numero)

#Exec2 Laços de Repetição - Vinicius Queiroz Santos
par = 0
while par <=20:
 if par % 2 == 0:
  print(par)
 par += 1

#Exec3 Laços de Repetição - Vinicius Queiroz Santos
soma = 0
for numero in range(5):
  entrada_numero = int(input("Digite um número: "))
  soma += entrada_numero
print("A soma dos números é:", soma)

#Exec4 Laços de Repetição - Vinicius Queiroz Santos
while True:
  palavra = input("Digite uma palavra: ")
  if palavra == "sair":
    break
  print(palavra)

#Exec5 Laços de Repetição - Vinicius Queiroz Santos
numero_tabuada = int(input("Digite um número para gerar a tabuada: "))
for multiplicador in range(1, 11):
  resultado = numero_tabuada * multiplicador
  print(f"{numero_tabuada} x {multiplicador} = {resultado}")

#Exec6 Funções - Vinicius Queiroz Santos
def saudar(name):
  print(f"Olá, {name}! Seja muito bem vindo")

saudar("Vinicius")

#Exec7 Funções - Vinicius Queiroz Santos
def somar(num1,num2):
    return num1 + num2

resultado = somar(num1=10,num2=15)
print(resultado)

#Exec8 Funções - Vinicius Queiroz Santos
def impar_par(numero):
  if numero % 2 == 0:
    return "par"
  else:
    return "impar"

numero = int(input("Digite um número: "))
# Correção: o nome da função estava digitado errado
resultado = impar_par(numero)
print(f"O número {numero} é {resultado}.")

#Exec9 Funções - Vinicius Queiroz Santos
def calcular_fatorial(numero):
  if numero == 0:
    return 1
  else:
    fatorial = 1
    for i in range(1, numero + 1):
      fatorial *= i
    return fatorial

numero = int(input("Digite um número para calcular o fatorial: "))
resultado = calcular_fatorial(numero)
print(f"O fatorial de {numero} é {resultado}.")

#Exec10 Funções - Vinicius Queiroz Santos
def nomes(lista_nome):
  for nome in lista_nome:
    print(nome)

nomes(["Vinicius","Gustavo","Davi", "Thomas"])

#Exec11 Operações Condicionais - Vinicius Queiroz Santos
idade = int(input("Digite sua idade: "))
if idade >= 18:
  print("Você é maior de idade.")
else:
  print("Você é menor de idade.")

#Exec12 Operações Condicionais - Vinicius Queiroz Santos
numero1 = int(input("Digite o primeiro número: "))
numero2 = int(input("Digite o segundo número: "))
if numero1 > numero2:
  print(f"O número {numero1} é maior que o número {numero2}.")

#Exec13 Operações Condicionais - Vinicius Queiroz Santos
nota = float(input("Digite sua nota: "))
if nota >= 7:
  print("Aprovado")
else:
  print("Reprovado")

#Exec14 Operações Condicionais - Vinicius Queiroz Santos
numero = int(input("Digite um número: "))
if numero < 0:
  print(f"O número {numero} é negativo.")
elif numero == 0:
  print(f"O número {numero} é zero.")
else:
  print(f"O número {numero} é positivo.")

#Exec15 Operações Condicionais - Vinicius Queiroz Santos
senha = int(input("Digite sua senha: "))
if senha == 1234:
  print("Acesso permitido")
else:
  print("Pah, Acesso negado")

#Exec16 Operações Condicionais - Vinicius Queiroz Santos
while True:
  print("\n Menu de Opções ")
  print(" 1- Saque. ")
  print(" 2- Depósito. ")
  print(" 3- Sair. ")
  opcao = int(input("Digite uma opção: "))

  if opcao == 1:
    print("Você escolheu a opção 1 - Saque.")
  elif opcao == 2:
    print("Você escolheu a opção 2 - Depósito.")
  elif opcao == 3:
    print("Você escolheu a opção 3 - Sair.")
    break

#Exec17 Operações Condicionais - Vinicius Queiroz Santos
dia = int(input("Digite o dia da semana(1,2,3,4,5,6,7): "))
if dia == 1:
  print("Domingo")
elif dia == 2:
  print("Segunda-feira")
elif dia == 3:
  print("Terça-feira")
elif dia == 4:
  print("Quarta-feira")
elif dia == 5:
  print("Quinta-feira")
elif dia == 6:
  print("Sexta-feira")
elif dia == 7:
  print("Sábado")

#Exec18 Operações Condicionais - Vinicius Queiroz Santos
letra = input("Digite uma letra: ").lower()
if letra in 'aeiou':
    print(f"A letra '{letra}' é uma vogal.")
else:
    print(f"A letra '{letra}' é uma consoante.")

#Exec19 Operações Condicionais - Vinicius Queiroz Santos
def calculadora():
    operacao = input("Digite a operação (+, -, *, /): ")
    num1 = float(input("Digite o primeiro número: "))
    num2 = float(input("Digite o segundo número: "))

    if operacao == '+':
        resultado = num1 + num2
    elif operacao == '-':
        resultado = num1 - num2
    elif operacao == '*':
        resultado = num1 * num2
    elif operacao == '/':
        if num2 != 0:
            resultado = num1 / num2
        else:
            print("Erro: divisão por zero.")
            return
    else:
        print("Operação inválida.")
        return

    print(f"Resultado: {resultado}")

calculadora()

#Exec20 Operações Condicionais - Vinicius Queiroz Santos
personagem = int(input("Selecione seu personagem (1 - Guerreiro, 2 - Mago, 3 - Arqueiro): "))

if personagem == 1:
    print("Você selecionou o Guerreiro!")
elif personagem == 2:
    print("Você selecionou o Mago!")
elif personagem == 3:
    print("Você selecionou o Arqueiro!")
else:
    print("Opção inválida. Selecione um número entre 1 e 3.")